name: job_offers_daily

on:
  workflow_dispatch:
    inputs:
      search_terms:
        description: "Mots-clés pour la recherche (ex: serveur logé, aide barman logé, vendanges logé)"
        type: string
        required: true
        default: "serveur logé, aide barman logé, runner logé, vendanges logé, ouvrier cave logé, aide caviste logé, employé polyvalent logé, cueilleur logé"

  schedule:
    - cron: "0 7 * * *"
    - cron: "0 8 * * *"

jobs:
  crawl_and_send:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Paris
      OPENAI_MODEL: gpt-5
      OPENAI_TEMPERATURE: "0"
      OPENAI_CHUNK_SIZE: "24"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip
          pip install "httpx<0.28"
          pip install requests beautifulsoup4 lxml html5lib backoff "openai==1.51.0" pyflakes

      - name: Guard 09:00 Europe/Paris (éviter les doublons)
        env:
          GITHUB_EVENT_NAME: ${{ github.event_name }}
        run: |
          set -euo pipefail
          NOW_HOUR="$(date +'%H')"
          if [ "$GITHUB_EVENT_NAME" = "schedule" ] && [ "$NOW_HOUR" != "09" ]; then
            echo "Skipping, current hour: $NOW_HOUR (target 09:00 Europe/Paris)"
            exit 0
          fi

      - name: Write sites.json
        run: |
          set -euo pipefail
          printf '%s\n' \
          '[' \
          '  "francetravail","indeed","hellowork","meteojob","adzuna","alljobs","linkedin","google_jobs","lesjeudis","leboncoin","manpower"' \
          ']' > sites.json
          cat sites.json

      - name: Write filters.json
        run: |
          set -euo pipefail
          printf '%s\n' \
          '{' \
          '  "must_have_housing": true,' \
          '  "min_duration_days": 7,' \
          '  "max_duration_days": 92,' \
          '  "allow_only_metropole": true,' \
          '  "exclude_corse": true,' \
          '  "exclude_domcom": true,' \
          '  "allowed_jobs": [' \
          '    "serveur","serveuse","runner","aide de salle","aide barman","commis de bar",' \
          '    "vendangeur","porteuse","porteur","trieur","ouvrier agricole polyvalent",' \
          '    "ouvrier de cave","aide caviste","employe polyvalent","employé polyvalent",' \
          '    "cueilleur","cueilleuse"' \
          '  ]' \
          '}' > filters.json
          cat filters.json

      # ---- Étape 1 : récolte de SEEDS (recherche) ----
      - name: Write fetch_sites.py
        run: |
          set -euo pipefail
          printf '%s\n' \
          "import json, os, requests" \
          "SITES = json.load(open(\"sites.json\",\"r\",encoding=\"utf-8\"))" \
          "TERMS = os.getenv(\"SEARCH_TERMS\", \"\").strip() or \"${{ github.event.inputs.search_terms }}\"" \
          "def q(s): return requests.utils.quote(s)" \
          "def results_indeed(t): return [{\"source\":\"indeed\",\"url\":f\"https://fr.indeed.com/jobs?q={q(t)}+log%C3%A9&l=France\",\"title\":\"Indeed: \"+t}]" \
          "def results_hellowork(t): return [{\"source\":\"hellowork\",\"url\":f\"https://www.hellowork.com/fr-fr/emploi/recherche.html?k={q(t)}+logement\",\"title\":\"HelloWork: \"+t}]" \
          "def results_francetravail(t): return [{\"source\":\"francetravail\",\"url\":f\"https://candidat.francetravail.fr/offres/recherche?k={q(t)}&l=France\",\"title\":\"France Travail: \"+t}]" \
          "def results_simple(engine, t): return [{\"source\":engine,\"url\":f\"https://www.google.com/search?q=site%3A{engine}.com+{q(t)}+log%C3%A9+France\",\"title\":engine+\" via Google\"}]" \
          "DISPATCH = {\"indeed\":results_indeed,\"hellowork\":results_hellowork,\"francetravail\":results_francetravail}" \
          "raw=[]" \
          "terms=[x.strip() for x in TERMS.split(\",\") if x.strip()] or [\"serveur logé\",\"aide barman logé\",\"runner logé\",\"vendanges logé\",\"ouvrier cave logé\",\"aide caviste logé\",\"employé polyvalent logé\",\"cueilleur logé\"]" \
          "for site in SITES:" \
          "  for t in terms:" \
          "    fn=DISPATCH.get(site)" \
          "    raw.extend(fn(t) if fn else results_simple(site,t))" \
          "json.dump(raw, open(\"offers_raw.json\",\"w\",encoding=\"utf-8\"), ensure_ascii=False, indent=2)" \
          "print(\"Collected seeds:\", len(raw))" \
          > fetch_sites.py
          python -m pyflakes fetch_sites.py || true
          python fetch_sites.py

      # ---- Étape 2 : mapping/notation par GPT — 1 sortie PAR SEED ----
      - name: Write filter_with_gpt.py
        run: |
          set -euo pipefail
          printf '%s\n' \
          "import json, os, re" \
          "import backoff, httpx" \
          "from openai import OpenAI" \
          "from openai import APIConnectionError, RateLimitError, APIStatusError, APITimeoutError" \
          "" \
          "MODEL = os.getenv(\"OPENAI_MODEL\",\"gpt-5\")" \
          "TEMP = float(os.getenv(\"OPENAI_TEMPERATURE\",\"0\"))" \
          "CHUNK_SIZE = int(os.getenv(\"OPENAI_CHUNK_SIZE\",\"24\"))" \
          "" \
          "client = OpenAI(api_key=os.getenv(\"OPENAI_API_KEY\"), timeout=120.0, max_retries=2)" \
          "" \
          "offers = json.load(open(\"offers_raw.json\",\"r\",encoding=\"utf-8\"))" \
          "filters = json.load(open(\"filters.json\",\"r\",encoding=\"utf-8\"))" \
          "" \
          "allowed = [a.lower() for a in filters.get(\"allowed_jobs\", [])]" \
          "" \
          "sys_prompt = {\"role\":\"system\",\"content\":\"Tu reçois des entrées {source,url,title}. POUR CHAQUE entrée, rends EXACTEMENT 1 objet offre. NE SUPPRIME RIEN. Champs: {source,title,company,offer_url,offer_id,employer_email,score,note}. Règles: 1) offer_url = url d'entrée; 2) company vide si inconnue; 3) pour France Travail, si l'URL contient /offres/recherche/detail/<id> alors offer_id=<id>, sinon vide; 4) email uniquement si présent littéralement (sinon vide); 5) score 0-100: +60 si le titre contient 'logé' ou 'logement', +20 si le titre contient un métier autorisé; clamp 0..100. Réponds en JSON strict {offers:[...]}.\"}" \
          "" \
          "@backoff.on_exception(backoff.expo, (APIConnectionError, httpx.RemoteProtocolError, httpx.ConnectError, httpx.ReadTimeout, RateLimitError, APIStatusError, APITimeoutError), max_tries=6, jitter=backoff.full_jitter)" \
          "def call_openai(payload):" \
          "  return client.chat.completions.create(model=MODEL, temperature=TEMP, response_format={\"type\":\"json_object\"}, messages=[sys_prompt,{\"role\":\"user\",\"content\": json.dumps(payload, ensure_ascii=False)}])" \
          "" \
          "def chunks(lst, n):" \
          "  for i in range(0, len(lst), n):" \
          "    yield lst[i:i+n]" \
          "" \
          "def seed_fallback(seed):" \
          "  t = (seed.get(\"title\") or \"\").strip()" \
          "  u = (seed.get(\"url\") or \"\").strip()" \
          "  s = (seed.get(\"source\") or \"\").strip()" \
          "  tl = t.lower()" \
          "  score = 0" \
          "  if \"logé\" in tl or \"logement\" in tl: score += 60" \
          "  for a in allowed:" \
          "    if a in tl: score += 20; break" \
          "  if score > 100: score = 100" \
          "  oid = \"\"" \
          "  if \"francetravail\" in u:" \
          "    m=re.search(r\"/offres/recherche/detail/([A-Za-z0-9_-]+)\", u)" \
          "    if m: oid=m.group(1)" \
          "  return {\"source\":s, \"title\":t, \"company\":\"\", \"offer_url\":u, \"offer_id\":oid, \"employer_email\":\"\", \"score\":score, \"note\":\"fallback\"}" \
          "" \
          "agg=[]" \
          "for idx, part in enumerate(chunks(offers, CHUNK_SIZE), start=1):" \
          "  payload={\"filters\":filters, \"offers\":part}" \
          "  out=[]" \
          "  try:" \
          "    resp=call_openai(payload)" \
          "    data=json.loads(resp.choices[0].message.content)" \
          "    out=data.get(\"offers\",[])" \
          "  except Exception:" \
          "    out=[]" \
          "  if not out or not isinstance(out,list):" \
          "    out = [seed_fallback(it) for it in part]" \
          "  elif len(out) != len(part):" \
          "    while len(out) < len(part):" \
          "      out.append(seed_fallback(part[len(out)]))" \
          "    if len(out) > len(part):" \
          "      out = out[:len(part)]" \
          "  agg.extend(out)" \
          "  print(f\"Chunk {idx}: +{len(out)} items\")" \
          "" \
          "seen=set(); dedup=[]" \
          "for it in agg:" \
          "  url=(it.get(\"offer_url\") or it.get(\"url\") or \"\").strip()" \
          "  oid=(it.get(\"offer_id\") or \"\").strip()" \
          "  key=url or oid or ((it.get(\"source\") or \"\")+\"|\"+(it.get(\"title\") or \"\"))" \
          "  if key and key not in seen:" \
          "    seen.add(key); dedup.append(it)" \
          "" \
          "json.dump({\"offers\":dedup}, open(\"offers_filtered.json\",\"w\",encoding=\"utf-8\"), ensure_ascii=False, indent=2)" \
          "print(\"Done. Total items:\", len(dedup))" \
          > filter_with_gpt.py
          python -m pyflakes filter_with_gpt.py || true

      - name: Run filtering (GPT)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          set -euo pipefail
          python filter_with_gpt.py

      # ---- Étape 3 : Email (URL cliquable, pas de répétition source) ----
      - name: Write email_report.py
        run: |
          set -euo pipefail
          printf '%s\n' \
          "import os, smtplib, json" \
          "from email.mime.multipart import MIMEMultipart" \
          "from email.mime.text import MIMEText" \
          "RECIPIENT = os.getenv(\"RECIPIENT_EMAIL\") or \"indrix.mk@gmail.com, stellameftah@gmail.com\"" \
          "SENDER = os.getenv(\"SENDER_EMAIL\")" \
          "SMTP_HOST = os.getenv(\"SMTP_HOST\")" \
          "SMTP_PORT = int(os.getenv(\"SMTP_PORT\"))" \
          "SMTP_USER = os.getenv(\"SMTP_USER\")" \
          "SMTP_PASS = os.getenv(\"SMTP_PASS\")" \
          "def pretty_source(raw):" \
          "    m={\"francetravail\":\"France Travail\",\"hellowork\":\"HelloWork\",\"indeed\":\"Indeed\",\"meteojob\":\"MeteoJob\",\"adzuna\":\"Adzuna\",\"alljobs\":\"AllJobs\",\"linkedin\":\"LinkedIn\",\"google_jobs\":\"Google Jobs\",\"lesjeudis\":\"Les Jeudis\",\"leboncoin\":\"Le Bon Coin\",\"manpower\":\"Manpower\"}" \
          "    s=(raw or \"\").strip().lower(); return m.get(s, raw or \"?\")" \
          "data = json.load(open(\"offers_filtered.json\",\"r\",encoding=\"utf-8\"))" \
          "items = data.get(\"offers\", []) if isinstance(data, dict) else []" \
          "html=[\"<h2>Offres saisonnières - Rapport</h2>\",\"<ol>\"]" \
          "for it in items[:200]:" \
          "    src=pretty_source(it.get(\"source\",\"?\"))" \
          "    title=(it.get(\"title\") or \"Offre\").strip()" \
          "    tl=title.lower(); sl=src.lower()" \
          "    if tl.startswith(sl): title=title[len(src):].lstrip(\" :-–—|\")" \
          "    company=(it.get(\"company\") or \"—\").strip()" \
          "    score=str(it.get(\"score\",\"?\"))" \
          "    mail=(it.get(\"employer_email\") or \"—\").strip()" \
          "    link=(it.get(\"offer_url\") or it.get(\"url\") or \"\").strip()" \
          "    url_field = (\"<a href=\"+\"\\\"\"+link+\"\\\"\"+\">URL</a>\") if link else \"URL indisponible\"" \
          "    line = \"{0}: {1} - {2} - Score: {3} - {4} - {5}\"" \
          "    li = \"<li>\" + line.format(src, title, company, score, url_field, mail) + \"</li>\"" \
          "    html.append(li)" \
          "html.append(\"</ol>\")" \
          "msg=MIMEMultipart(\"alternative\"); msg[\"Subject\"]=\"Veille offres saisonnières (agrégées)\"; msg[\"From\"]=SENDER; msg[\"To\"]=RECIPIENT" \
          "msg.attach(MIMEText(\"\\n\".join(html),\"html\",\"utf-8\"))" \
          "with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as s:" \
          "    s.starttls(); s.login(SMTP_USER, SMTP_PASS); s.sendmail(SMTP_USER, [x.strip() for x in RECIPIENT.split(\",\") if x.strip()], msg.as_string())" \
          "print(\"Email sent to\", RECIPIENT)" \
          > email_report.py

      - name: Send email
        env:
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENTS }}
          SENDER_EMAIL: ${{ secrets.SMTP_FROM }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
        run: |
          set -euo pipefail
          python -m pyflakes email_report.py || true
          python email_report.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: job_offers
          path: |
            sites.json
            filters.json
            offers_raw.json
            offers_filtered.json