name: jobsearch

on:
  schedule:
    - cron: '0 7 * * *'  # 09:00 Europe/Paris (été UTC+2 => 07:00 UTC) / (hiver UTC+1 => 08:00 UTC)
  workflow_dispatch:
    inputs:
      origin_city:
        description: "Ville de départ pour le tri (par défaut Clermont-Ferrand, France)"
        required: false
        default: "Clermont-Ferrand, France"
      max_results:
        description: "Nombre max d'offres (par défaut 30)"
        required: false
        default: "30"
      sectors:
        description: "Secteurs (ex: hotellerie-restauration,agri-vendanges)"
        required: false
        default: "hotellerie-restauration,agri-vendanges"
      housing_required:
        description: "Filtrer logement requis (true/false), par défaut true"
        required: false
        default: "true"

permissions:
  contents: read

concurrency:
  group: jobsearch-daily
  cancel-in-progress: false

jobs:
  search-and-email:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Upgrade pip and install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml geopy

      - name: Run search and send mail
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          SMTP_FROM: ${{ secrets.SMTP_FROM }}
          RECIPIENTS: ${{ secrets.RECIPIENTS }}
          NOMINATIM_EMAIL: ${{ secrets.NOMINATIM_EMAIL }}
          FALLBACK_CONTACTS: ${{ secrets.FALLBACK_CONTACTS }}
          ORIGIN_CITY: ${{ github.event.inputs.origin_city || 'Clermont-Ferrand, France' }}
          MAX_RESULTS: ${{ github.event.inputs.max_results || '30' }}
          SECTORS: ${{ github.event.inputs.sectors || 'hotellerie-restauration,agri-vendanges' }}
          HOUSING_REQUIRED: ${{ github.event.inputs.housing_required || 'true' }}
        run: |
          python scripts/job_search.py